### ISSUE TITLE
bug：idea等图标无法正常展示。建议：每次搜索重新读取项目。

### ISSUE THREAD

**Issue by enximi** [devotion-coding/utools-plugin-quick_open_jetbrains#2]
pycharm项目和idea项目的图标都显示为空白。如下。
![image](https://github.com/devotion-coding/utools-plugin-quick_open_jetbrains/assets/70036307/272111b0-f21c-411e-be30-916105a9250f)
可能是 `getFileIcon` 输入的路径有空格的时候获取图标会失败。
另外，能不能每次使用搜索重新读取一次所有项目，消耗应该没多大，但是新建项目就不用重启utools了。

**Comment by devotion-coding** [comment]
每次唤醒插件时重建项目列表 以发布应用市场最新版本V1.0.5
图标问题后续处理

**Comment by devotion-coding** [comment]
v1.0.8 版本中修复，应用市场已送审
